name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop, release-*]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Code Analysis
        run: yarn lint:check

      - name: Node.js Scan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'

      - name: Security Scan
        run: yarn audit

      - name: Notify Team on Lint Failure
        if: failure()
        run: echo 'Lint or security scan failed. Please check the workflow logs.'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test
